### ISSUE TITLE
Ability to turn off for specific tests

### ISSUE THREAD

**Issue by lloydwatkin** [WeTransfer/wt_activerecord_index_spy#20]
**Is your feature request related to a problem? Please describe.**
When running rspec tests it would be great if I could annotate a test/suite/etc so it doesn't do any checking whilst the test is running. 

**Describe the solution you'd like**
For example:
```ruby
it 'does not need an index because the table has two rows', :skip_index_spy do
  expect(Model.active.count).to eq 2
end
```

**Describe alternatives you've considered**
I've been reworking my code up to this point as much as possible to get around the problem.

**Comment by lloydwatkin** [comment]
I _think_ I may have solved using this the following setup for my tests:

```ruby
  config.around(:each) do |example|
    expect { example.run }.to(have_used_db_indexes) unless example.metadata[:skip_index_spy]
  end

  config.after(:all) do
    WtActiverecordIndexSpy.export_html_results(File.new(File.join(Rails.root, "tmp/wt_activerecord_index_spy-results.html"), "w"))
  end
```

**Comment by fabioperrella** [comment]
That's a nice suggestion! 

But it can be confusing if someone uses like this:
```ruby
it 'does xyz', :skip_index_spy do
  expect { x }.to have_used_db_indexes
end
```

wdyt?

**Comment by lloydwatkin** [comment]
Possibly, but us developers have the ability to do many conflicting and silly things if we want :)

**Comment by fabioperrella** [comment]
haha, that's true!

Feel free to send a PR adding this if you want.

**Comment by lloydwatkin** [comment]
Updated in readme here 6e05d0e256b1a8109ff67ecfd21d2ee27fb1d432
